### ISSUE TITLE
We REALLY need this!

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/contact-api#20]
As I argued over in the Mozilla positions repository, it seems that Apple has been able to provide this functionality without requiring an API:
https://github.com/mozilla/standards-positions/issues/153#issuecomment-486481303

<img width="299" alt="Look ma, no API!" src="https://user-images.githubusercontent.com/870154/56702909-cf515c00-6749-11e9-809f-67b4aa2c3b8d.png">

It simply uses existing HTML autocomplete, and implicit grants similar to file API to allow one to both pick and autofill a contact. Further, it doesn't have significant privacy issues, because it never leaks the contacts to the site. The user has to explicitly select a contact to autofill.

**Comment by beverloo** [comment]
I do like the auto fill approach, but I think it has some important limitations that make the two features complementary. Some initial thoughts, @rayankans will likely have more ideas -

- It doesn't scale very well when you need to select more than a single contact. This reflects use-cases we hear from quite a few developers, ranging from group messaging to social network bootstrapping.
- It doesn't scale very well when contacts have multiple e-mail addresses or phone numbers, for instance private and public ones. User controls would allow selecting _which_ to share, rather than multiple.
- It might be insufficient for data types beyond text, unless we treat them as a file upload of sorts? (#13)

**Comment by rayankans** [comment]
Thanks @beverloo, you pretty much covered all the points I wanted to make :)

The HTML autocomplete method definitely has its advantages, but only for a limited set of use-cases (if you want to upload a few contact fields). The proposed API offers more flexibility in terms of the website's UI, as well as an easier flow for more complicated use-cases (multiple contacts, icon uploads...).

@marcoscaceres, do you mind expanding a bit further on what you mean by the significant privacy issues? With HTML autocomplete the site still has access to the shared contacts. The Contact API gives one-off access only to the *explicitly* selected contacts, so nothing is leaked.

Do we REALLY need this? Well do we REALLY need any API? I think this API offers a simple, privacy-conscious solution to a very requested web feature. It's also powerful enough to cover all use-cases, without having to use workarounds. That's not to say that autocomplete doesn't have its place. I agree that they can be complementary as @beverloo said.

**Comment by aarongustafson** [comment]
Agree with @beverloo and @rayankans here. Also, for whatever it's worth, without knowing that @beverloo was working on this, I began designing a Contacts API predicated on privacy (I lived through the Path debacle all those years ago) and on protecting users from oversharing other people's information. Funny enough, it was pretty much identical in it's approach. It's a very transparent (to users) design, controllable without being overwhelming from a UI perspective, scalable, and follows an explicit request model that's demonstrated success, both as a technology and in terms of developer excitement (e.g., SOAP, GraphQL).

**Comment by marcoscaceres** [comment]
> The Contact API gives one-off access only to the explicitly selected contacts, so nothing is leaked.

Ah, I'd missed that bit. Thanks for clarifying (as well as the additional use cases). Thanks also @aarongustafson. 

I'm still on the fence on this, but keenly watching to see where it goes.

**Comment by marcoscaceres** [comment]
As an aside, there may be some overlap with:
https://www.w3.org/TR/payment-request/#paymentaddress-interface

That is, it may be possible to somehow use `PaymentAddress` to provide the contact address information (despite the crappy Payment* name :)).

**Comment by rayankans** [comment]
Thanks @marcoscaceres, I suggested re-using `PaymentAddress` [here](https://github.com/WICG/contact-api/issues/12#issuecomment-493483827), but yeah we should be able to rename it to something more general since it's not constructable :)

**Comment by marcoscaceres** [comment]
Agree... we can subclass it and add a constructor for it. Something like: 

```
[constructor(AddressInit)]
interface ContactAddress extends PaymentAddress {};
```

I'd like to eventually move "PaymentAddress" to its own spec... if we can enhance PaymentAddress  to make it more universal, that would would be great.

**Comment by cedvdb** [comment]
@marcoscaceres 

I need clarification. Will this contact API be used for, for example selecting a user in the contacts of an user and get his information ( tel / email ) ? Because your contact input seems to be for sending the current user information.

This would be really helpful for invitations in a PWA application

**Comment by marcoscaceres** [comment]
Deferring to @rayankans...

**Comment by rayankans** [comment]
@cedvdb it could be used for either, which is why returning a `ContactInfo` object works better as it can account for both cases (uploading to a server / using the info within the client).

**Comment by cedvdb** [comment]
What would generally be the timeline for something like to go from proposal to an actual implementation ? Can I vote somewhere ?

**Comment by marcoscaceres** [comment]
Votes don’t help (in this case) - but review of the actual API and helping us refine it sure do. As per implementation, that’s a harder one, specially across two browsers.

**Comment by marcoscaceres** [comment]
Closing, as there is nothing actionable here.
