### ISSUE TITLE
Unable to register for Origin Trial

### ISSUE THREAD

**Issue by Exoplanet3000** [WICG/contact-api#27]
I've successfully implemented the Contact Picker API in my Reactjs project, an app where friends can buy Starbucks for friends - try it out here [](https://foodmigo.com) - However, when I go to the Origin Trials console, it's stuck on "Loading..."....I've contacted Original Trial support, 404 no help found. 

If anybody would be kind enough to share their token, I & the foodmigo would sincerely appreciate it!! :)

**Comment by tomayac** [comment]
I've just gone through the [sign-up process](https://developers.chrome.com/origintrials/#/register_trial/85568392920039425) and it worked just fine. Could you try again, please? Maybe a browser extension on your system is blocking something?

**Comment by Exoplanet3000** [comment]
> I've just gone through the [sign-up process](https://developers.chrome.com/origintrials/#/register_trial/85568392920039425) and it worked just fine. Could you try again, please? Maybe a browser extension on your system is blocking something?

Ahh, yes I was blocking the Google cookies...problem solved! Thanks!
