### ISSUE TITLE
Handling contact addresses

### ISSUE THREAD

**Issue by rayankans** [WICG/contact-api#43]
The ContactAddress interface used to rely on the PaymentAddress interface which has since been dropped. This raises a few questions:
- Is this the right spec to define addresses?
- Should the current interface be changed to have closer HTML/autocomplete alignment?

**Comment by marcoscaceres** [comment]
* Is this the right spec to define addresses?

It's as good an any. 

* Should the current interface be changed to have closer HTML/autocomplete alignment?

That might be good, but it really depends on how much implementer appetite there is for renaming/refactoring things. 

I think we should maybe just provide a non-normative mapping in the spec for now... if we start seeing people complain, we can look at renaming things.
